name: Install GStreamer from Packages
description: Installs the GStreamer using packages at either the URLs or local paths
inputs:
  version:
    description: 'GStreamer version to install (ignores url and path variables)'
    required: false
  version-ref:
    description: 'GStreamer version ref to install (required if version is specified)'
    required: false
  s3-download-paths:
    description: 'S3 paths to download from (required if version is specified)'
    required: false
  install-development:
    description: 'Install GStreamer development packages (in addition to runtime)'
    required: false
    default: 'true'
  runtime-installer-url:
    description: 'URL of the GStreamer runtime installer'
    required: false
  development-installer-url:
    description: 'URL of the GStreamer development installer (required if install-development)'
    required: false
  runtime-installer-path:
    description: 'Local path of the GStreamer runtime installer'
    required: false
  development-installer-path:
    description: 'Local path of the GStreamer development installer (required if install-development)'
    required: false
outputs:
  install-dir:
    description: 'GStreamer install directory'
    value: ${{ steps.install-gstreamer.outputs.gstreamer-install-dir }}
  plugin-dir:
    description: 'GStreamer plugin directory'
    value: ${{ steps.install-gstreamer.outputs.gstreamer-plugin-dir }}
  bin-dir:
    description: 'GStreamer bin directory'
    value: ${{ steps.install-gstreamer.outputs.gstreamer-bin-dir }}

runs:
  using: "composite"
  steps:
    - if: runner.os == 'Windows'
      id: setup-msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        path-type: inherit
        release: false

    - if: ${{ runner.os != 'Windows' }}
      shell: msys2 -eo pipefail {0}
      run: |
        echo "::error This action is only supported on Windows at this time; pull requests welcome!"
        exit 7

    - name: Determine installation method(s) from inputs and output path(s) to install files
      id: resolve
      shell: ${{ runner.os == 'Windows' && 'msys2 -eo pipefail {0}' || 'bash' }}
      env:
        S3_DOWNLOAD_PATHS: ${{ inputs.s3-download-paths }}
      run: |
        runner_os="${{ runner.os }}"
        version="${{ inputs.version}}"
        version_ref="${{ inputs.version-ref }}"
        include_development="${{ inputs.install-development }}"
        runtime_installer_url="${{ inputs.runtime-installer-url }}"
        development_installer_url="${{ inputs.development-installer-url }}"
        runtime_installer_path="${{ inputs.runtime-installer-path }}"
        development_installer_path="${{ inputs.development-installer-path }}"

        # output vars for later steps
        runtime_path=""
        development_path=""
        result=0

        s3_find_installer() {
          local paths="${1:?Download paths are required as an array}"
          local version="${2:?Version is required}"
          local uri=""

          for download_path in ${paths}; do
            local bucket=$(echo ${download_path} | cut -d/ -f3)
            local prefix=$(echo ${download_path} | cut -d/ -f4-)

            file_path=$(aws s3api list-objects-v2 --bucket "${bucket}" --prefix "${prefix}/" --query 'sort_by(Contents, &LastModified)[].Key' | jq -r 'if type!="array" then [] else . end | sort_by(length) | map(select(contains("'"${version}"'"))) | .[0]')
            if [ "null" != "${file_path}" ]; then
              uri="s3://${bucket}/${file_path}"
            fi
          done
          echo "${uri}"
        }

        download_installer() {
          local uri="${1}"
          local file_name=$(echo "${uri}" | rev | cut -d/ -f1 | rev)
          local local_path="$(pwd)/${file_name}"
          local result=1

          if [ -n "${uri}" ]; then
            if [ "$(echo "${1}" | cut -c1-5)" = "s3://" ]; then
              aws s3 cp --no-progress "${uri}" "${local_path}" &>> download.log
              result=$?
            else
              curl -L -O "${uri}" -o "$local_path" &>> download.log
              result=$?
            fi
          fi

          if [ $result -eq 0 ]; then
            echo "${local_path}"
          else
            echo ""
          fi
        }

        version_prefix=""
        if [ ${runner_os} == 'Windows' ]; then
          version_prefix="msvc-x86_64-"
        fi

        version="${version_prefix}${version}"
        if [ -n "${version_ref}" ]; then
          version="${version}-${version_ref}"
        fi

        if [ -f "${runtime_installer_path}" ]; then
          runtime_path="${runtime_installer_path}"
        elif [ -n "${runtime_installer_url}" ]; then
          runtime_path=$(download_installer "${runtime_installer_url}")
        else
          runtime_installer_url=$(s3_find_installer "${S3_DOWNLOAD_PATHS[@]}" "${version}")
          runtime_path=$(download_installer "${runtime_installer_url}")
        fi

        if [ -n "${runtime_path}" ]; then
            if [ ${runner_os} == 'Windows' ]; then
              runtime_path=$(cygpath -aw "${runtime_path}")
            fi
          echo "runtime=$runtime_path" | tee -a $GITHUB_OUTPUT
        else
          echo "::error No GStreamer runtime installer found"
          result=1
        fi

        if [ "true" == "${include_development}" ]; then
          if [ -f "${development_installer_path}" ]; then
            development_path="${development_installer_path}"
          elif [ -n "${development_installer_url}" ]; then
            development_path=$(download_installer "${development_installer_url}")
          else
            development_installer_url=$(s3_find_installer "${S3_DOWNLOAD_PATHS[@]}" "devel-${version}")
            development_path=$(download_installer "${development_installer_url}")
          fi

          if [ -n "${development_path}" ]; then
            if [ ${runner_os} == 'Windows' ]; then
              development_path=$(cygpath -aw "${development_path}")
            fi
            echo "development=$development_path" | tee -a $GITHUB_OUTPUT
          else
            echo "::error No GStreamer development installer found"
            result=1
          fi
        fi
        exit $result

    - if: ${{ runner.os == 'Windows' }}
      name: Install GStreamer
      id: install-gstreamer
      shell: powershell
      env:
        RUNTIME_MSI: ${{ steps.resolve.outputs.runtime }}
        DEVELOPMENT_MSI: ${{ steps.resolve.outputs.development }}
      run: |
        $GSTREAMER_INSTALL_DIR="${{ runner.temp }}\gstreamer"
        $GSTREAMER_ROOT="$GSTREAMER_INSTALL_DIR\1.0\msvc_x86_64"
        $GSTREAMER_BIN="$GSTREAMER_ROOT\bin"
        echo "$GSTREAMER_BIN" | Out-File -FilePath $Env:GITHUB_PATH -Append -Encoding utf8
        echo "PKG_CONFIG_PATH=$GSTREAMER_ROOT\lib\pkgconfig;$env:PKG_CONFIG_PATH" | Out-File -FilePath $Env:GITHUB_ENV -Append -Encoding utf8

        echo "gstreamer-bin-dir=$GSTREAMER_BIN" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append -Encoding utf8
        echo "gstreamer-install-dir=$GSTREAMER_INSTALL_DIR" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append -Encoding utf8
        echo "gstreamer-plugin-dir=$GSTREAMER_ROOT" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append -Encoding utf8

        Write-Output "::notice Using runtime: $Env:RUNTIME_MSI"
        Write-Output "::notice Using development: $Env:DEVELOPMENT_MSI"

        if (Test-Path -Path "$Env:RUNTIME_MSI") {
          Write-Output "::notice title=Installing GStreamer Runtime"
          $proc = Start-Process msiexec -ArgumentList "/i `"$Env:RUNTIME_MSI`" ADDLOCAL=ALL INSTALLDIR=`"$GSTREAMER_INSTALL_DIR`" /qn /l*vx runtime-install.log" -NoNewWindow -PassThru -Wait
          if ($proc.ExitCode -ne 0) {
            Write-Output "::error title=GStreamer Runtime installation failed with exit code $($proc.ExitCode)"
            Get-Content runtime-install.log
            exit $proc.ExitCode
          }

          if (Test-Path -Path "$Env:DEVELOPMENT_MSI") {
            Write-Output "::notice title=Installing GStreamer Development"
            $proc = Start-Process msiexec -ArgumentList "/i `"$Env:DEVELOPMENT_MSI`" ADDLOCAL=ALL INSTALLDIR=`"$GSTREAMER_INSTALL_DIR`" /qn /l*vx development-install.log" -NoNewWindow -PassThru -Wait
            if ($proc.ExitCode -ne 0) {
              Write-Output "::error title=GStreamer Development installation failed with exit code $($proc.ExitCode)"
              Get-Content development-install.log
              exit $proc.ExitCode
            }
          }
        } else {
          Write-Output "::error title=GStreamer is not installed."
          exit 999
        }
