name: Build GStreamer

on:
  push:
    # branches: ['*.*-lldc']
    # tags: ['*.*.*-lldc*']
  pull_request:
  workflow_dispatch:
    inputs:
      cerbero-repo:
        description: 'Cerbero repository to use (defaults to the current repository)'
        required: false
      cerbero-ref:
        description: 'Cerbero ref to use (defaults to the current ref)'
        required: false

jobs:
  build-gstreamer-for-windows:
    name: Build GStreamer for Windows
    runs-on: floor-to-ceiling-windows-latest-runner
    steps:
      - name: Get GStreamer installer S3 prefix
        id: s3-prefix
        if: vars.GSTREAMER_S3_UPLOAD_PREFIX
        shell: bash
        run: |
          prefix="${{ vars.GSTREAMER_S3_UPLOAD_PREFIX }}/${GITHUB_HEAD_REF:-${GITHUB_REF_NAME:-${GITHUB_REF##*/}}}"
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            prefix="${prefix}-${{ github.run_number }}"
          fi
          echo "prefix=${prefix}" | tee -a $GITHUB_OUTPUT

      - id: build-gstreamer
        name: Build GStreamer
        uses: ./.github/actions/build-gstreamer-for-windows
        with:
          cerbero-repo: ${{ inputs.cerbero-repo || github.repository }}
          cerbero-ref: ${{ inputs.cerbero-ref || github.ref }}
          force: true
          s3-download-paths: >-
            ${{ vars.GSTREAMER_S3_UPLOAD_BUCKET && vars.GSTREAMER_S3_UPLOAD_PREFIX && format('s3://{0}/{1}', vars.GSTREAMER_S3_UPLOAD_BUCKET, vars.GSTREAMER_S3_UPLOAD_PREFIX) || '' }}
            ${{ vars.GSTREAMER_S3_UPLOAD_BUCKET && steps.s3-prefix.outcome != 'skipped' && format('s3://{0}/{1}', vars.GSTREAMER_S3_UPLOAD_BUCKET, steps.s3-prefix.outputs.prefix) || '' }}
          s3-upload-path: >-
            ${{ vars.GSTREAMER_S3_UPLOAD_BUCKET && vars.GSTREAMER_S3_UPLOAD_PREFIX && format('s3://{0}/{1}', vars.GSTREAMER_S3_UPLOAD_BUCKET, vars.GSTREAMER_S3_UPLOAD_PREFIX) || '' }}

      - name: Annotate workflow run with GStreamer version
        if: steps.build-gstreamer.outputs.gstreamer-version
        run: |
          echo "::notice title=Using GStreamer version ${{ steps.build-gstreamer.outputs.gstreamer-version }}::Used installer with Cerbero short sha ${{ steps.build-gstreamer.outputs.cerbero-short-sha }}"
